version: "3.8"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge